### ISSUE TITLE
Add ability to silence command output

### ISSUE THREAD

**Issue by vdice** [deislabs/porter-helm#15]
Currently, the `helm` command invoked via the corresponding porter (mixin) action is printed out to the console.

This can be handy for confirming the command looks as intended and certainly seems the sane default.  However, the command may contain secret/sensitive data (for instance, `helm install ... --set secret=supersecret`).  

Therefore, it may be nice to optionally silence this command output.  One use case that comes to mind is automated/CI runs where logs may be publicly accessible.

**Comment by carolynvs** [comment]
Is the problem verbosity, or is the real problem that porter isn't hiding secret info? Think of more mature build system, they would help *** out secrets from the logs. Maybe we should be doing that too?

**Comment by vdice** [comment]
Mmm, indeed, it's more the latter (not hiding secret info).  Shall we update this ticket to narrow focus towards hiding secrets?

Perhaps the UX would be an optional `secret` boolean field for each secret key/value pair added under the `set:` block to indicate its needing to be silenced?  And/or, perhaps, if the value comes in the form of a `credentials.<value>` it should _always_ be masked?

**Comment by carolynvs** [comment]
I lean towards always masking anything that was passed into the bundle as a credential as an environment value, without requiring further markup. No need to mask file paths such as `/root/.kube/config` since the contents of the file are secret, but not the path, and right now porter just passes around the path (and that's what shows up in the logs).

I see that in our azure wordpress example, the `mysql_password` is a parameter, not a credential which I would call out as a bug in our example? I'm guessing we did that so that we could default the password, but shouldn't it have been a credential? Let me know if I'm ascribing too much to the difference between a credential and a parameter. I am just hesitant to introduce a porter specific attribute to a CNAB field (parameter).

Another way for secrets to pop up in logs is for outputs from a step to get wired into subsequent steps. So flagging an output as secret (i.e. flag it at the source) should help us treat it as secret.

```yaml
install:
- description: "Install MySQL"
  helm:
    name: porter-ci-mysql
    chart: stable/mysql
    version: 0.10.2
    replace: true
  outputs:
  - name: mysql-root-password
    secret: porter-ci-mysql
    key: mysql-root-password
    sensitive: true
  - name: mysql-port
    secret: porter-ci-mysql
    key: mysql-port
    #sensitive defaults to false 
```
