### ISSUE TITLE
Proposal: <Action>Arguments uses Charts map 

### ISSUE THREAD

**Issue by vdice** [deislabs/porter-helm#5]
Here I'll focus on the only action currently implemented, `Install`, but it would/could apply for the rest of the to-be-implemented actions (status, upgrade, uninstall).

`InstallArguments` currently takes one `Chart` (and associated info).  So, each install block only enables a one-to-one chart to install action, like so:

```
  - description: "Helm Install foo"
    helm:
      name: foo
      chart: foo
      values: foo-values.yaml

  - description: "Helm Install bar"
    helm:
      name: bar
      chart: bar
      values: bar-values.yaml
```

Here the proposal is to switch `InstallArguments` to take a `Charts` map (to new `Chart` object/struct) instead, so that one block can run the same (install) action on more than one charts, like so:

```
  - description: "Helm Install charts"
    helm:
      charts: 
        foo:
          chart: foo
          values: foo-values.yaml
        bar:
          chart: bar
          values: bar-values.yaml
```

Where the key of each entry would be the Helm release name and the value represents the Chart object.  This would still support the use case where only one chart is needed per action (simply only add one chart to `charts`).

The action logic would then loop over the `Charts` map and execute, in sequence, the appropriate action against each chart.

**Comment by carolynvs** [comment]
I'm worried that this may make some of the porter wiring more complicated or unavailable entirely. Let's think about a few scenarios and walk through them to check. If you could reply back with some example yaml of what each scenario would look like, that would really help us think this through:

1. Not requiring a values.yaml for a chart and allowing people to continue to use name, version replace, set, etc directly in the porter manifest. See https://github.com/deislabs/porter/blob/2001b09190c331445bd33485444348f9f61054fc/build/testdata/bundles/mysql/porter.yaml#L26-L34 for an example.
2. Allowing people to wire a chart value from the bundle `e.g. source: bundle.parameters.FOO`, see https://github.com/deislabs/porter/blob/2001b09190c331445bd33485444348f9f61054fc/build/testdata/bundles/wordpress/porter.yaml#L34 for an example.
3. I believe that it's not desirable for charts that are batched together to depend upon each other (i.e. use outputs generated from the other chart, such as `source: bundle.outputs.CHART_A_THING`. 

In general this feature seems like an optimization that may decrease usability, for the sake of less typing and I'm not even quite sure how much typing in reality it saves. So having some full examples of those scenarios (and examples of how it saves typing, ideally from what prompted you to ask for this feature with before and after yaml manifests) would really help us design this out! 😀

**Comment by vdice** [comment]
@carolynvs thank your for the feedback. To reiterate/clarify, the use case is a bundle that manages a large number of chart releases on a K8s cluster.  The specific case for myself is a cluster that hosts a Brigade server/dashboard/gateway charts, many Brigade projects, auxiliary charts such as an ingress controller, cert manager, etc. -- all configured via corresponding Helm charts and values.

> To be clear I'm not saying "this isn't useful" I'm saying that in the snippet we are only including chart and values.yaml but we'd also need release name, chart version, set, and other values too, right? 

Definitely, yes.  All existing chart-level configuration currently supported would persist and migrate to a new Chart struct/object.

I'm envisioning the implementation would continue to support all of the main points 1-3 above.  Here's an example that I believe covers them:
```
mixins:
  - helm
 
name: example
version: 0.1.0
invocationImage: example:latest

credentials:
- name: EXAMPLE_CRED
  env: EXAMPLE_CRED

parameters:
- name: example_param
  type: string
  default: example

install:
  - description: "Install prereq charts"
    helm:
      charts: |
        foo:
          chart: chartrepo/foo
          version: 1
          values: foo/values.yaml
          set:
            cred: 
              source: bundle.credentials.EXAMPLE_CRED
        bar:
          chart: chartrepo/bar
          version: 2
          replace: true
          set:
            param: 
              source: bundle.parameters.example_param
    outputs: |
      foo:
        - name: foo-output
          key: foo-value
      bar:
        - name: bar-output
          key: bar-value

  - description: "Install other/auxiliary charts"
    helm:
      charts: |
        baz:
          chart: chartrepo/baz
          set:
            foo.value:
              source: bundle.outputs.foo-output
        lol:
          chart: chartrepo/lol
          set:
            bar.value:
              source: bundle.outputs.bar-output

# For purposes of example, the upgrade action definition would look identical to install above
upgrade:
  - description: "Upgrade prereq charts"
    helm:
      charts: |
        foo:
          ...
        bar:
          ...
    outputs: |
      foo:
        ...
      bar:
        ...

  - description: "Upgrade other/auxiliary charts"
    helm:
      charts: |
        baz:
          chart: chartrepo/baz
          ...
        lol:
          chart: chartrepo/lol
          ...

status:
  - description: "Check status of all chart releases"
    helm:
      charts: |
        foo
        bar
        baz
        lol

uninstall:
  - description: "Uninstall all chart releases"
    helm:
      charts: |
        foo
        bar
        baz
        lol
```

I do concede that the benefits of consolidation/less typing arguably may not be enough to compensate for a possible degradation of usability.  After reviewing the example above, what do you think?
