### ISSUE TITLE
Enhancement: Add helm repo support via mixin config

### ISSUE THREAD

**Issue by vdice** [deislabs/porter-helm#60]
As a user of this mixin needing to fetch charts from chart repos, I would like a way to specify which chart repos should be fetched at build-time via mixin config.  Something like this in a `porter.yaml`:

```yaml
mixins:
- helm:
    repos:
      brigade:
        url: https://brigadecore.github.io/charts
      linkerd:
        url: https://helm.linkerd.io/stable
```

Inspired by https://github.com/deislabs/porter-helm/issues/8#issuecomment-473788262, the current thinking is that a repo entry may contain additional fields in the future (supporting auth credentials or other), but for this first iteration, the single `url` property seems sufficient.

This mixin would then be in charge of parsing the configuration and adding the relevant repo add commands into the build steps (Dockerfile lines), e.g. `helm repo add brigade https://brigadecore.github.io/charts`, etc.

There is prior art in consuming such extra mixin configuration; see the [az mixin](https://github.com/deislabs/porter-az).

This ticket supersedes the original issue/design in https://github.com/deislabs/porter-helm/issues/8
