### ISSUE TITLE
Enhancement: add helm repo support

### ISSUE THREAD

**Issue by vdice** [deislabs/porter-helm#8]
I'm wondering if we can add helm repo support to this mixin.

Currently, to fetch non-default helm repos, I have an exec step in my porter.yaml under the `install` action:
```
  - exec:
      description: "Add Helm repos"
      command: bash
      arguments:
        - -c
        - "helm repo add brigade https://azure.github.io/brigade-charts"
```

It would be neat if this mixin added first-class support for helm repo add/upgrade.

I could see this being either via standalone stanza:
```
  - helm:
      description: "Add Helm repos"
      repos:
        brigade: https://azure.github.io/brigade-charts
        ...
```
or paired with the chart that requires it:
```
  - helm:
      description: "Helm install Brigade"
      name: brigade
      chart: brigade/brigade
      repo: 
        brigade: https://azure.github.io/brigade-charts
        ...
```
Thoughts?

**Comment by carolynvs** [comment]
I vote for option 1

**Comment by vdice** [comment]
This seems like a great candidate for a `good first issue`.  To that end, after talking with @carolynvs , we've decided to pursue implementing for the first option above:

```
  - helm:
      description: "Add Helm repos"
      repos:
        brigade: https://azure.github.io/brigade-charts
        ...
```

Here are some pointers for the implementation:

- In [install.go](https://github.com/deislabs/porter-helm/blob/master/pkg/helm/install.go), we can create a new `Repos` struct that can be a `map[string]string`, with each key representing the chart repo name and each value representing the chart repo URL. 
- In the same file, we can add logic to parse this data from the provided yaml into their go struct counterparts and execute a `helm repo add <repo name> <repo URL>` command
- In the corresponding [install_test.go](https://github.com/deislabs/porter-helm/blob/master/pkg/helm/install_test.go), we can add appropriate new test(s).

At this time, I think we should be good with just adding/amending the `install`-related files, since once the repos have been added to the local helm repository listing, they will be available on the system for any further actions.

**Comment by jdolitsky** [comment]
Take a look at what Helmfile project is doing for this:
https://github.com/roboll/helmfile

```
repositories:
  - name: roboll
    url: http://roboll.io/charts
    certFile: optional_client_cert
    keyFile: optional_client_key
    username: optional_username
    password: optional_password
```
